### ISSUE TITLE
Inference scripts

### ISSUE THREAD

**Issue by kr-sundaram** [devJWSong/transformer-translator-pytorch#1]
Thanks for make this repo public. Could you please help me in getting to know how to generate translate for new sentence?

**Comment by devjwsong** [comment]
Thank you for visiting my repo.
Since yesterday was Sunday, I noticed this issue now. Sorry for the late response.

I think you know that the inference works with a different mechanism than the training part.
When training, both source input and target input are put at once into the encoder/decoder since the transformer can process all tokens in parallel unlike the traditional RNN-based seq2seq model.
But in testing, we cannot feed the target sequence at once because we do not know the answer.
So just like the traditional seq2seq, we should generate each word sequentially, add it, and feed the sentence made so far as the target sequence until the [EOS] comes out.

More specifically, we only have [SOS] token so the target input becomes [SOS] [PAD] [PAD] ... [PAD] in the beginning.
After making one word, the target input becomes [SOS] [WORD1] [PAD] .... [PAD].
This is put into the decoder again.
This iteration goes on and on until the target input becomes [SOS] [WORD1] [WORD2] .... [WORDN] [EOS] [PAD]...[PAD].
That's why the inference code has a for loop for this iteration procedure.

I posted about this repo in [my personal tech blog](https://songstudio.info/tech/tech-25/), so maybe it can help you to understand the codes.

Additionally, this is a greedy method, which is not recommended these days.
I will update my repo after implementing the beam search soon, so you can check that also.

If you have any question, feel free to notify me.
Thank you.

**Comment by kr-sundaram** [comment]
Thank you so much for your explanation!

I would like to develop a production level machine translation model like google’s or Microsoft’s.

I have few queries and hope you can help me understanding how to incorporate those features in order to develop a robust NMT model.

1. It’s a good practice to have our model trained on as much as data we could but still there is a limitation of data availability. What do you think how data will be sufficient for this task?

2. How to handle transliteration of named entities and translation in the same model as we can see in MarianMT translation models in huggingface.

3. How to handle the casing, dates and punctuations in the translated sentences as that of the source sentences. Whether we need to have huge corpus in order to make the model learn or is there any specific way to do so?

Thank you for your patience! :)

**Comment by devjwsong** [comment]
I'm not sure that I can be a big help for you, but I will try to answer your questions as far as I know.

1. As you said, yes, we need a huge data to build a robust NMT model. We cannot specify the exact size of corpus, but with 150,000 pairs, I could not get desirable results with the transformer. (Maybe due to my poor training techniques...?) And the original corpus has about 2,000,000 pairs, so I think you can guess how many samples you need. This is [the link](https://www.statmt.org/europarl/) of Europarl Parallel Corpus instruction. You can check the size of each parallel data to assume the size you need. And this is [the link](http://www.statmt.org/wmt20/) for WMT, which is a famous NMT conference. I think it can also help you.

2.  First, I've never heard of Marian MT and thank you for your useful information. Second, I'm not sure that I understand your question correctly. Is it about how we can convert named entities in source language into proper words in target language with a more sophiscated method than simple learning? For now, this repo is just a simple practice for transformer implementation to NMT, so transliteration of named entities is not considered right now. And I don't know how to handle this, but it is worth thinking. Of course, it is the best to train a model to deal with these entities with a huge and diverse corpus. In my opinion, one simple method might be making a look-up table to convert an entity name into target language. But I bet this is not a very good idea since a programmer should set the table manually. Since NMT is not my professional field, I'm sorry for my deficient answer. I will notify you when I find a decent insight about it.

3. I think this is also a similar problem with the question #2 since all of them can be considered as special words. And I don't understand what "casing" is, so I will answer about dates and punctuations. Again, it is the best to make the model handle these with huge data, I think and I don't know how MS or Google handled these situations. We can think of various options. First, I think it will be helpful if we convert date expressions into special token, such as [DATE]. Since this does not change the meaning of the sentences and reduces noises from complicated date expressions, reverting this token into original date value after the translation seems nice to me. And removing punctuation itself does not hurt the structure of the sentences not much, but maybe harmful to the meaning. (Since some have a special meaning, ?: question, !: surprise...etc.) But the translation is a directed generation task. We just have to make a target sentence just considering the structure without deep understanding of input meaning. So if you think that removing punctuation is beneficial to training, it can also be an option. But after the translation, you should put punctuation back with additional method, such as POS tagger or rule-based algorithm.

Again, I'm not sure that I gave you useful info, but thank you for your interest in me and my repo.
Please let me know if you have another question.

Thank you.

**Comment by kr-sundaram** [comment]
Thank you very much for all your kind help!
